### ISSUE TITLE
Explain GitHub Actions test suite only fires at ember-flight-icons/ dir

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#102]
Test seem to be stalled on https://github.com/hashicorp/flight/pull/100

Maybe related to implementing vercel?

![image](https://user-images.githubusercontent.com/1372946/130657853-305251ec-e7d6-4b6a-a26b-1820c5c1014f.png)

**Comment by Dhaulagiri** [comment]
This is because they are [configured](https://github.com/hashicorp/flight/blob/5299cc8b81e7fd88b53f2a3390bffc60c1bdd7cc/.github/workflows/ci-ember-flight-icons.yml#L44) to only run if something in the ember addon changes. This is pretty confusing and breaks the ability to require them to pass though...

**Comment by amyrlam** [comment]
oh i see, thanks for pointing that out. never seen that before in tests, but haven't worked on too many addons.

should we consider having export-go output to `ember-flight-icons/`, or is that not the addon way?

**Comment by Dhaulagiri** [comment]
I don't know that we'd want to consider something like that just to get the tests to behave a certain way. It'd be more a question of how we want the icon workflow to behave between figma/github.

**Comment by amyrlam** [comment]
yeah makes sense, i meant more to not have 2 copies of icons. but is a tangent, will keep the issue scoped!

for this, i think i can at least add something to the readme or PR template that explains this? will propose something in a PR
