### ISSUE TITLE
Determine how to deal with css overrides that may exist

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#120]
Thanks for starting to test this @amyrlam! And good catch @didoo - looks like they are applying strokes to the icons in that section via CSS, so our icon path is gaining the extra stroke which is making it thicker. We're probably going to come up against custom CSS like this quite a bit.

<img width="304" alt="CleanShot 2021-08-27 at 10 53 02@2x" src="https://user-images.githubusercontent.com/717867/131109331-ea6d760f-4e9d-470c-ada4-043a9da70346.png">

If we discard that CSS rule the arrow looks correct (and imo is visually more balanced against the text weight than the previous ones which is great!)

<img width="1270" alt="CleanShot 2021-08-27 at 10 52 53@2x" src="https://user-images.githubusercontent.com/717867/131109342-4ff2bbf9-2d57-4092-842f-7fe47c839058.png">

_Originally posted by @dizzyup in https://github.com/hashicorp/flight/issues/60#issuecomment-907080529_

**Comment by didoo** [comment]
I think we should speak with the team and come up with a shared agreement on how to deal with this. 
Some options I see here (but early stage, still to validate/check in reality):
- ask to remove the stroke (at least understand why it's used and in which context, and come up with an alternative, eg. a specific class added to the "old" icons so that they use this style, but not all the icons by default)
- ask to apply a specific class to the Flight icons (or some very very specific CSS selector that targets only the Flight icons, but this may be a bad idea) that removes the value of the stroke so that the Flight icons are not affected

**Comment by amyrlam** [comment]
related to / overlaps with https://github.com/hashicorp/flight/issues/123, please see https://github.com/hashicorp/hashicorp-www-next/pull/2267/commits/be4926761898f2645e174a0d63beb0ef88420baa

i'm meeting with jmfury tomorrow to talk about their team executing next steps

**Comment by didoo** [comment]
@amyrlam what was the outcome of the meeting? something that we have to do on our side? or they'll fix it on their?

**Comment by amyrlam** [comment]
@didoo marketing fixed it here https://github.com/hashicorp/hashicorp-www-next/pull/2285. we still need to get https://github.com/hashicorp/hashicorp-www-next/pull/2267 on marketing's project management radar

i made a new asana ticket to split up marketing, since they'll be different project management tickets in their external asana/jira's. i think that this could be closed and can instead track here: https://app.asana.com/0/1200639100898494/1200943875242646

please reopen if you disagree though!

**Comment by didoo** [comment]
@amyrlam OK for me
