### ISSUE TITLE
Fix how colored icons are shown in the miniwebsite

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#185]
In #179 we've added the newly generated SVGs to the mini-website. They now contain also the colored icons, but for some reasons the mini website is using the mono icons also for the colored ones. See screenshot below:

<img width="1792" alt="screenshot_67" src="https://user-images.githubusercontent.com/686239/132906962-fe0938a3-f8ac-4907-ada4-cd5c658eb0bd.png">

**Comment by Dhaulagiri** [comment]
The reason this is happening is because the ember component is being passed the [icon name](https://github.com/hashicorp/flight/blob/823a3580ca20dcd417765b7aa3b653fc0871f2a4/src/flight-icons-exported/catalog.json#L7575) which in this case is `slack` and then it appends the size on depending on the `size` property that is passed in.

@didoo would it make sense to have the `iconName` in these cases be something like `slack-color` to differentiate between the mono version that would be just `slack`?

**Comment by didoo** [comment]
@Dhaulagiri if you look in the `catalog.json` file, you will see that I have differentiated between the `iconName` (in case of one of the services, eg. `aws`) and the `fileName` (in that case, is something like `aws-color-16`)

you should use the file name for the SVG and the icon name for the display in the UI

**Comment by didoo** [comment]
<img width="1097" alt="screenshot_68" src="https://user-images.githubusercontent.com/686239/132908642-e7bc6c54-4cbd-4c9f-bb88-20950e6d687a.png">

**Comment by didoo** [comment]
@Dhaulagiri which means that in the code (until we decide how to handle this `mono/color` difference) you have to parse the file name via regex and remove the `/(.*)(-\d{2})$/` part

/cc @MelSumner

**Comment by didoo** [comment]
@Dhaulagiri after discussion with @dizzyup, we've agreed to "fix" this on the Figma side, so we will have two different "icons"  for the same service/entity:

<img width="894" alt="screenshot_71" src="https://user-images.githubusercontent.com/686239/133072171-62bf748c-1b11-4611-a2ff-1718022e7c0e.png">

this should automatically fix the issue above. let me do the changes and then we can come back to this
