### ISSUE TITLE
Generation of the CSS/SCSS files 

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#197]
@johncowen as discussed yesterday with you and @amyrlam, I have committed a first draft of the function that generates the CSS/SCSS files with Flight Icons embedded as `data:image` elements (as already mentioned, this is to facilitate the adoption of the icon set in Consul, but expect in the future to have possible alternative/preferred ways to consume them)

You can see the function in the PR #196:
https://github.com/hashicorp/flight/blob/171-node-icon-export-library-script-build/flight-icons/scripts/build-parts/generateBundleCSS.ts

I have tried to follow the logic I see in your PR to Iris:
https://github.com/johncowen/iris/pull/1/files

and this is the generated file in output (we don't commit the `dist` folder at the moment):
[flight-icons-forconsul.scss.zip](https://github.com/hashicorp/flight/files/7161151/flight-icons-forconsul.scss.zip)

from what I understand/see from your scrip, I expect that you can consume directly this file as installed npm package, and in your PR mentioned above you have to remove the reference to the “flight” icons, just process your local SVGs and structure files, and then update line 94 with the correct naming 

Do you think this would work?

**Comment by didoo** [comment]
After meeting and discussion with @amyrlam and @johncowen, the decision was that he prefers to have a single point of control for the assets, so he will use the custom script he developer in https://github.com/johncowen/iris/pull/1/files

We will then remove the CSS generation from the assets pipeline (will be extremely easy to rebuild it, or look at the git history to revert the changes).

**Comment by johncowen** [comment]
Just to add here I would much rather use something from the design team, but also I don't want to have to maintain another script for the icons we only use in Consul. Ideally we would just use the script made for this issue and ditch the stuff I cobbled together a while ago. Otherwise we will have to keep syncing any differences between the 2 scripts to keep the output of flight and custom icons the same, which is not ideal.

We floated an idea of passing the path to our custom icons to the script created as part of this issue so we only have one script that doesn't need syncing. I'd be happy to help with that if that was something folks wanted to do, then we could get rid of the image generation stuff in iris entirely and just use DS stuff.

If not please do keep the files around as I would like to integrate some of the work you did into iris as there we some improvements you made there that I'd like to keep.

**Comment by didoo** [comment]
> If not please do keep the files around as I would like to integrate some of the work you did into iris as there we some improvements you made there that I'd like to keep.

Sure! I have attached the files: 
[Archive.zip](https://github.com/hashicorp/flight/files/7164978/Archive.zip)
