### ISSUE TITLE
Update Ember Addon to inline the SVG sprite and not reference it as external resource

### ISSUE THREAD

**Issue by didoo** [hashicorp/flight#198]
There is an issue with using the SVG sprite as external resource:

```
<svg>
    <use href="/@hashicorp/ember-flight-icons/icons/sprite.svg#bitbucket-color-24"></use>
</svg>
```
vs instead inlining the SVG sprite in the page and then referencing it via its ID:

```
<svg>
    <use href="#bitbucket-color-24"></use>
</svg>
```

When used in the first way, the "definitions" in the sprite are not considered (see couple of links at the bottom).

This means that the gradients applied to the icons are not rendered in the Ember addon (that's why we have the issue mentioned by @Dhaulagiri in https://github.com/hashicorp/flight/pull/193#issuecomment-918628049. At the beginning I thought it was because of non unique IDs (which was also a problem, but then it was fixed but the issue remained), so I made a quick test (see [test.zip](https://github.com/hashicorp/flight/files/7162012/test.zip); you can serve the folder via `python -m SimpleHTTPServer 8000`) and yes, the issue is with the external reference:

<img width="163" alt="screenshot_77" src="https://user-images.githubusercontent.com/686239/133260347-c0391e79-9c72-4363-86dd-fb50581b2d19.png">

@MelSumner @Dhaulagiri do you think there is a way to fix this in the Ember addon? (embedding the SVG in the page, instead of referencing it as remote resource?) I know we're losing the benefit of caching a resource (btw, in that case probably we should have some cache-busting mechanism in place, for when the sprite is updated, otherwise a user may not see the updates) but I don't know any alternative, I've always used inline SVGs.

The alternative may be to get rid of the gradient at all in Figma but:
- we are playing with other companies logos, not good
- we may want in the future include ourselves icons with gradients

------

Relevant links
- https://fvsch.com/svg-gradient-fill
- https://stackoverflow.com/questions/63898270/linear-gradient-in-svg-symbol-while-using-svg-sprite

**Comment by MelSumner** [comment]
I can try it but we have already been told that caching is not an issue, because most product consumers have to run the entire app locally anyway (or something like that).

**Comment by didoo** [comment]
@MelSumner so if caching is not an issue, let's have the SVG embedded in the page (don't know how to do it in Ember, otherwise I would have opened a PR)

**Comment by Dhaulagiri** [comment]
FWIW I ran into issues with the sprite being cached testing docs changes yesterday. I had to clear my cache in order to see the changes I made to the sprite reflected between builds. This should be a solvable problem, though.

**Comment by didoo** [comment]
@MelSumner just to clarify: when you say "caching is not an issue" you mean size of the file is not an issue, or stale cache is not an issue?

**Comment by amyrlam** [comment]
- The original idea with a sprite was that it would be cached on AWS CDN or similar, with a very long TTL, and purged when we bumped the version. Since some apps like Nomad are self-hosted on the customer, everything is packaged up on their own servers, they would not be able to access a file cached externally on AWS.
- The browser caching that @Dhaulagiri is a different caching issue that we should look into. Name the sprite with a version # or use fingerprinting to bust the browser cache?

I don't fully understand this issue yet, but I'll take a look later. I'm going to focus on https://github.com/hashicorp/flight/pull/196 first, which relates to this issue.

**Comment by MelSumner** [comment]
We did also try this the streamlined way, but it wasn't working properly when we put it into apps. In the end we're more like giving it an abs path rather than calling an external resource, aren't we? Maybe I am missing something.

**Comment by amyrlam** [comment]
It may make sense for me to look at this issue today, will @ in Slack

**Comment by Dhaulagiri** [comment]
@amyrlam and I took a stab at this in https://github.com/hashicorp/flight/pull/245 and found we could confirm the approach solves the issue described here and also works in the docs and in a project like waypoint. Attempts to verify it worked in cloud-ui were unsuccessful but it was hard to verify exactly _why_ due to issues locally link the package under yarn 3. My assumption is that we might have been running into the same issue @MelSumner ran into initially that led her to create [this logic](https://github.com/hashicorp/flight/blob/cbbacf708dc6e6cfeaa26229ee3975c3c7139482/ember-flight-icons/addon/components/flight-icon.js#L7-L10), but we also didn't errors I would have expected either.
