### ISSUE TITLE
Sprite loading performance

### ISSUE THREAD

**Issue by Dhaulagiri** [hashicorp/flight#226]
We currently embed the sprite into the ember addon which is convenient, but has a side effect of introducing a situation where the sprite is not loaded until after the app loads. See below:

<img width="954" alt="Screen Shot 2021-09-16 at 13 25 03" src="https://user-images.githubusercontent.com/1672302/133665170-e4dcbca4-cd20-4cac-9b38-d280023fc7b0.png">

In practice this means that icons can't load until after content starts rendering which creates a sub-optimal experience depending on a user's connection speed:

![icons-2](https://user-images.githubusercontent.com/1672302/133664961-b9c3185c-13fd-4dad-b0be-1c1d9b91e296.gif)
![icons](https://user-images.githubusercontent.com/1672302/133664964-792dbe61-e54a-4676-af14-78bc8c992176.gif)

**Comment by amyrlam** [comment]
Adding some notes for context of things we could try
- https://vercel.com/docs/edge-network/caching#static-files 
  - Doesn't seem like browser cache is an issue. Should confirm if .svg is considered a "static file", can find out
  - Doesn't seem like purging the cache is an issue, persisting if it doesn't change sounds good? 
- Add svg as extension here https://cli.emberjs.com/release/advanced-use/asset-compilation/#fingerprintingandcdnurls and see if the serve time on local dev with prod flag is faster?

**Comment by Dhaulagiri** [comment]
Caching/fingerprinting could help it load faster once it's requested but my current impression is that it's more an order of operations issue since the browser doesn't even know to start loading it until the app/vendor bundle loads and gets processed.

**Comment by amyrlam** [comment]
^^ makes sense 

I was mentioning that related to this comment re: browser caching: https://github.com/hashicorp/flight/issues/198#issuecomment-919319163

**Comment by didoo** [comment]
let's not forget to do also cache busting @amyrlam @Dhaulagiri @MelSumner

**Comment by amyrlam** [comment]
@didoo From the vercel docs, we don't need to CDN cache bust https://vercel.com/docs/edge-network/caching#static-files it's purged on its own if the file has changed

![image](https://user-images.githubusercontent.com/1372946/133838183-fb4cb06f-174b-4880-aad4-368968789536.png)

That being said I think fingerprinting the sprite and catalog sounds good to do anyways, is a very quick change I will do in a separate PR. Just want to clarify that this ticket is to work on the preload web perf. 

//

I haven't seen the browser cache issue that Brian mentioned https://github.com/hashicorp/flight/issues/226#issuecomment-921241953, but we should keep an eye on it.

**Comment by Dhaulagiri** [comment]
To clarify: I'm less concerned with the performance in Vercel than I am in apps that consume the addon.

**Comment by didoo** [comment]
> @didoo From the vercel docs, we don't need to CDN cache bust https://vercel.com/docs/edge-network/caching#static-files it's purged on its own if the file has changed
Ahh, now I see!

**Comment by amyrlam** [comment]
Ran out of time to type this out yest:

- The sprite.svg rn is 504 kB from Finder
![image](https://user-images.githubusercontent.com/1372946/133913843-687aaa32-39ab-4eb8-a37a-56fb0bed9699.png)

//

- Check out this branch locally (there's something weird with Vercel builds on `cloud-ui`, must request from meirish rn) https://github.com/hashicorp/cloud-ui/pull/1322
- Clear your browser data (incognito is kinda a PITA with the Okta / GitHub login) 
- Run `yarn && yarn start` from root
- On first load, takes 24ms:
![image](https://user-images.githubusercontent.com/1372946/133914013-64eb1800-970e-44dc-9a07-cf3382820fa3.png)
- On second load, takes 2ms:
![image](https://user-images.githubusercontent.com/1372946/133914029-e0a3476f-40b2-484f-89e3-67824b8a58bd.png)
- As you continue on, you can see it being the same size and time as the individual HashiCorp_white.svg:
![image](https://user-images.githubusercontent.com/1372946/133914087-a825cad7-cde4-4ca1-b3a9-b9453f35dc2f.png)
- @DingoEatingFuzz kindly pointed out that `cloud-ui` is using Amazon S3 CloudFront and also taught me quite a few things in the devtools I did not know before, thank you!

//

Suggested TODOs:

- [ ] I think we should fingerprint the sprite.svg even though it may not be necessary, so that it will be clear on say the CloudFront end 
- [ ] For https://flight-hashicorp.vercel.app/, we could consider adding a loading state e.g. a spinner before 

Not sure if we need to do anything else, lmk what you think.

**Comment by didoo** [comment]
@amyrlam as discussed during the planning session today, let's put this in the icebox for now because the issue is minor at this point. we can review the decision later, if we see it's a real issue that has a visible impact on the mini-website (and products) performance

**Comment by amyrlam** [comment]
sgtm

**Comment by Dhaulagiri** [comment]
After thinking on this some more and playing some other approaches I realized that they also suffered from the same issue and that there wasn't anything particularly actionable we could be doing differently here.
