### ISSUE TITLE
Docs site icon search field misbehaves on Safari

### ISSUE THREAD

**Issue by jgwhite** [hashicorp/flight#228]
As you’ll see in the video, as I type the input is erased and replaced with the last typed character (and the cursor position is reset).

https://user-images.githubusercontent.com/34030/133685405-ad1882c3-93c2-4662-9a8c-f50299978ced.mp4

**Comment by amyrlam** [comment]
Thanks for filing, I can repro.

FWIW Firefox looks good. 

I can take a look later today, or if you prefer to investigate @MelSumner please let me know!

**Comment by jgwhite** [comment]
> FWIW Firefox looks good

Chrome appears fine too, albeit with a curious behavior when trying to jump to the beginning/end of the value.

https://user-images.githubusercontent.com/34030/133691669-e6345875-b825-479b-8919-7fa7812d8bc5.mp4

**Comment by amyrlam** [comment]
Tricky one! Not sure _yet_ why the `event.target.value` is always overwritten by the most recent character typed in the input in Safari.

**Comment by amyrlam** [comment]
Talked to @MelSumner on Slack, she'll take this ticket and I'll take https://github.com/hashicorp/flight/issues/226, they both seem higher priority than other things rn

**Comment by MelSumner** [comment]
Update: 
I thought it was maybe that Safari didn't support the `AbortController` web API. That was a dead end because a polyfill is included in ember-fetch. 

I thought I might look at ember-mdi's demo app, since ours is similar. I pulled it up on Safari and noticed that while the live filter works (that one is in a controller not a component, and there is no size toggle), what shows up in the dom isn't correct, either: 

![image](https://user-images.githubusercontent.com/4587451/134036052-4236e2b6-d1cd-4a4a-ac1f-78981562a573.png)

So for our site, I'm going to look at how the value of the input is bound, and see if there's something specific to Safari that is required. 

I might need to look at what functionality should be moved to a controller vs keeping it in the component.

**Comment by MelSumner** [comment]
> Not sure _yet_ why the `event.target.value` is always overwritten by the most recent character typed in the input in Safari.

In chrome it's appended: 
![image](https://user-images.githubusercontent.com/4587451/134037062-11eb0bd1-a91e-432c-b755-9db70e43c992.png)

Safari it's replaced entirely: 
![image](https://user-images.githubusercontent.com/4587451/134037261-fc3afed0-ced8-4e48-9f94-5b2dfab5f0db.png)

**Comment by didoo** [comment]
@MelSumner I did a quick test and I noticed that if you comment out this
```
await new Promise((resolve) => setTimeout(resolve, 190));
```
it works as expected. Can you maybe try to use the old classic `setTimeout` to debounce and see if this strange behaviour disappears?

**Comment by jgwhite** [comment]
I think this might be a Safari browser bug, check this out:

https://user-images.githubusercontent.com/34030/134057779-6b276c9a-1812-4261-98eb-8a27efc7a03b.mp4

**Comment by MelSumner** [comment]
@jgwhite lol that's hilarious. I'll make that change. 👍

**Comment by jgwhite** [comment]
@MelSumner I think the trigger for this browser bug may be a little more subtle than that first video would suggest…

https://user-images.githubusercontent.com/34030/134059812-248981ed-f9fe-40a9-a9f7-8f81d44efc59.mp4
