### ISSUE TITLE
Add a title argument to the FlightIcon component

### ISSUE THREAD

**Issue by junyper** [hashicorp/flight#29]
I'd like to recommend adding a `title` optional argument.

Note: the last time I checked using `aria-labelledby` along with the `title` element worked consistently across screen readers to provide an accessible label for an inline SVG.

The template would be something like this:

```
<svg 
  aria-hidden={{unless (is-empty @title) "true"}}
  role={{if (is-empty @title) "presentation" "img"}}
  aria-labelledby={{this.titleId}}
  class="flight-icon icon-{{@name}} {{if this.display "display-inline"}}"
  data-test-icon={{@name}}
  fill={{this.fillColor}} 
  height="{{this.size}}"
  id={{this.iconId}}
  viewBox="0 0 {{this.size}} {{this.size}}"
  width="{{this.size}}" 
  xmlns="http://www.w3.org/2000/svg"
>
  {{#if @title}}
    <title id={{this.titleId}}>{{@title}}</title>
  {{/if}}
  <use href='{{this.baseURL}}/ember-flight-icons/icons/sprite.svg#{{@name}}-{{this.size}}'></use>
</svg>
```

With this implementation, developers would get the presentational markup by default, but could easily assign a title when it makes sense to do so.

**Comment by didoo** [comment]
@MelSumner also found this today, maybe it's relevant for the discussion above: as you can see icons are used as standalone assets, without textual counterpart or explicit context (apart from the tooltip). in that case do you think a "title" would help here? how would you make these icons more accessible in this case (and others similar)? or the tooltip provides the context?

<img width="1244" alt="screenshot_34" src="https://user-images.githubusercontent.com/686239/131583235-d6d35b96-b635-4ab7-b241-9b21ae361cfd.png">

see for example:
- https://learn-opa9qs86y-hashicorp.vercel.app/search?query=
- https://learn-git-kscard-updates-hashicorp.vercel.app/components?component=Card

(context: [this thread](https://hashicorp.slack.com/archives/C025N5V4PFZ/p1630441886032200))

**Comment by MelSumner** [comment]
@didoo in these cases, the tooltip and/or button/link would provide the context.

**Comment by amyrlam** [comment]
notes from the meeting with @didoo @junyper: 
- https://design-system.w3.org/styles/svg-icons.html#svg-accessibility
- approach in react: https://github.com/instructure/instructure-ui/blob/master/packages/ui-svg-images/src/InlineSVG/index.tsx
- current implementation

**Comment by didoo** [comment]
After meeting and discussion with @amyrlam and @junyper today, we have agreed to implement these changes for the 1.0 release of the Flight icons, because this is a blocker for them, for their adoption of the icons (they have multiple places where the icon is not just presentational).

What we have agreed is:
- to have an extra `title` prop added to the Ember addon component.
- if the `title` prop is specified by the consumer
   - the SVG `role` changes to `img`
   - we add a `<title>` element to the <svg> which contains an unique ID
   - the <svg> gets a `labeled-by` that points to that ID
   - the `<use href />` gets wrapped in a `<g>` element with a `aria-hidden="true"` applied to it

We will not add a `<description>` element because, very likely, is not used at all.

Please @junyper check if I am missing something above.
Please @MelSumner sync with @junyper if you have doubts or you think there may be alternative implementations.

Here for example how the W3C are doing this:
https://design-system.w3.org/styles/svg-icons.html#non-decorative-svg-accessibility

Here is a similar implementation done in React by @junyper:
https://github.com/instructure/instructure-ui/blob/master/packages/ui-svg-images/src/InlineSVG/index.tsx

**Comment by amyrlam** [comment]
The comments about the React marketing site (https://github.com/hashicorp/flight/issues/29#issuecomment-895487451) is separate issue as they are using the raw .svg's from @hashicorp/flight-icons, not @hashicorp/ember-flight-icons. I think we can extract that out more to the general idea that was mentioned even today, where the marketing folks are looking for a11y help, outside of the design system. I don't think there is a ticket for that but just explaining here so that the issue is scoped.

@MelSumner I'm happy to take this issue since I've been chugging away at `atlas` local dev (https://app.asana.com/0/1200639100898494/1200915812978043). If you feel strongly about it, can switch back? Will assign myself here and in Asana (this task is duped rn).
