### ISSUE TITLE
Set the value of the data-test-icon attribute to the name of the icon

### ISSUE THREAD

**Issue by junyper** [hashicorp/flight#31]
Small thing, but `<svg data-test-icon={{@name}} ...>` might be useful for testing?

**Comment by didoo** [comment]
In my previous company, what we did was to expose a `data-qa`* attribute/prop as an array of key/values, and convert each one of them to an HTML data-attribute, so that developers could attach any "data-qa" attribute to an element/component (each attribute was prefixed with "data-qa").

We could use a similar approach (but potentially a different naming convention, probably `data-test`?)

_* "qa" as in "quality assurance", so for testing_
