### ISSUE TITLE
Add "3rd party/services" assets to Flight Icons

### ISSUE THREAD

**Issue by amyrlam** [hashicorp/flight#35]
@Dhaulagiri @MelSumner I extracted this out into a separate ticket from https://github.com/hashicorp/flight/issues/13 and will leave it as `triage` 

@amyrlam said:

See if logo icons from other companies can be used with this approach. Sometimes, companies have restrictions on svg manipulation with their logos IIRC. This could be broken out into a separate issue if easier! re: https://hashicorp.slack.com/archives/C7KTUHNUS/p1628094787053200

//

@dizzyup said:

On the third-party logos: I asked around about this when I came across a similar concern documented in the old Structure Figma file - the latest on this was documented here: https://hashicorp.atlassian.net/browse/PDS-164?focusedCommentId=28263

The guidance from legal is that it’s ok to include logos in the design system. The owner of the individual application that leverages the design system should work with partner marketing to ensure they are using the logo in alignment with 3rd party logo guidelines.

I think it's reasonable to include the SVG logos in our icon system. There's a little complexity we need to account for though:

There is an additional variant that's introduced here so that in addition to size we can specify a style, "color" or "mono". The "mono" variants are identical to the regular Flight icons - ie. one flattened shape, with currentColor set as the fill. The other version, "color", has the colors embedded, and shouldn't accept fills.

![image](https://user-images.githubusercontent.com/1372946/128947010-7a40529c-4319-497e-87b2-0998a4ff2d8f.png)

**Comment by Dhaulagiri** [comment]
Note: The `needs rfc` label was applied due to the implication we might need to update our component's API to support color vs mono experience here, but we should revisit that to figure out if there is a simpler way to solve this.

**Comment by didoo** [comment]
I don't think we should consider these as special cases. It's only because one may think of Flight icons as mono-chromatic, but if instead the assumption is that icons can have explicit/intrinsic/fixed colors (like these) or dynamic/inherited colors (the "mono" ones) then we can make the assumption that even if one tries to assign a colored/third-party icon via inheritance and nothing happens, that's an acceptable result from the design system perspective.
What I mean is that this (pseudocode):
```
<Icon name="microsoft-color-16" color="#FF0000" /> 
```
should be an expected result to **not** see the icon in red, because as a user you're trying to apply a color to an icon that is not made for this.

In theory, in future, we may also have icons that have parts of the icon with fixed color(s), and parts of the icon with dynamic colors (that would inherit via currentColor). 

So for me the only investigation we need to do is about:
- if we want to support/add them to the library (@dizzyup what's your say about this?)
- what naming convention to use (if not already defined)
- how we update the import/sync script to do also these kind of icons (but maybe this could be tackled in the context of #28?)

**Comment by didoo** [comment]
After conversation with @dizzyup this morning we have agreed that this ticket becomes the main one about adding also the "3rd party/services" to the Flight Icons library (also, It doesn't need a RFC for this, so I am removing the label).

#20 will be incorporated in this one, so can be closed (also, the mapping is probably 1 to 1 between the old and the new icons).

/cc @Dhaulagiri

**Comment by Dhaulagiri** [comment]
Closed by https://github.com/hashicorp/flight/pull/164
