### ISSUE TITLE
Flight Icon Request: [enterprise]

### ISSUE THREAD

**Issue by braydenlove** [hashicorp/flight#387]
**Outline the use case for the new icon.**
An icon to describe an enterprise version of one of our products to be used on landing page cards.

**If there's a similar existing icon, why isn't it a good fit? Please describe.**
I am currently using org which looks like it could be enterprise. I worry about using it here if folks are use to seeing that icon in the actual products.

**Describe alternatives you've considered.**
Users (to describe multiple users)

**Screenshots**
![image](https://user-images.githubusercontent.com/81585949/149981569-08e04e1d-9d78-431c-ae15-ed1e47171301.png)

**Figma**
https://www.figma.com/file/rVuoJGNU6lr8UisTjtQNgj/Learn-IA-Jam?node-id=109%3A10759

**Additional context**
A few other requests incoming

**Comment by braydenlove** [comment]
Comment via @heatherlarsen
Enterprise idea: https://thenounproject.com/icon/enterprise-1584264/
add people to the buildings to help differentiate from the org icon, but still be similar?

**Comment by cveigt** [comment]
@heatherlarsen @braydenlove, that could work. I can try making a simplified version as it may be hard to read at 16px.

Here is another idea I wanted to run by you. Since the building icon is tied to organizations within HCP, also, the description refers to an enterprise product, not necessarily enterprise as an entity. Maybe something related to scale, global could help communicate this concept as well.

A few rough sketches.
<img width="1109" alt="Screen Shot 2022-01-21 at 11 53 01 AM" src="https://user-images.githubusercontent.com/2142312/150591565-359c9934-5404-4ccb-a796-52b6a8eb588d.png">

We already have a globe icon for more generic use-cases, I assume.
<img width="297" alt="Screen Shot 2022-01-21 at 11 53 37 AM" src="https://user-images.githubusercontent.com/2142312/150591660-9fc5cbb2-233e-4f69-8a05-f156685b6b2e.png">

Thoughts?

**Comment by braydenlove** [comment]
@cveigt I think these concepts would absolutely work. Thanks for sketching stuff out!

**Comment by cveigt** [comment]
We will be adding this icon in the next release.

<img width="129" alt="Screen Shot 2022-02-01 at 5 44 41 PM" src="https://user-images.githubusercontent.com/2142312/152080496-a9d41460-98ba-426f-8435-bafbf7de802f.png">

@braydenlove Let me know if you have any comments or feedback before publishing it on Figma and pushing it to production.

Here's an example of how it will look like in the Terraform card at 24px.

<img width="478" alt="Screen Shot 2022-02-01 at 5 51 59 PM" src="https://user-images.githubusercontent.com/2142312/152081052-af27ea4d-2d1c-48fd-a676-e926faa0f781.png">

**Comment by braydenlove** [comment]
Awesome work, thanks so much @cveigt
